apiVersion: v1
kind: Pod
metadata: 
  name: yellow
spec: 
    containers:
        - name: lemon
          image: busybox
          command: ['sh', '-c', 'echo The app is running! && sleep 55600']
        - name: gold
          image: redis
