apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod-test
  labels:
      tier: backend
      type: test
spec: 
    containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - mountPath: /var/log/nginx
              name: my-volume
    volumes:
      - name: my-volume
        persistentVolumeClaim: # point to pvc
            claimName: claim-log1