apiVersion: v1
kind: Pod
metadata: 
  name: red
spec: 
    containers:
        - name: gold
          image: redis
    initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', "sleep 20"]
        
