apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: finance
spec:
    replicas: 2
    selector:
        matchLabels:
          app: redis-app      
    template:
        metadata:
            labels:
                app:  redis-app   
        spec:
            containers:
            - name:  redis-container
              image: redis
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
    
              