apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
  labels:
    run : ingress-default-backend 
spec:
  ports:
  - name: port-backend
    port: 8080 # port service
    targetPort: 8080 #port container
  selector:
      run : ingress-default-backend
