apiVersion: v1
kind: Pod
metadata:
  name : blue-de
spec:
  containers:
    - name: blue-de-container
      image : nginx
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
