apiVersion: v1
kind: Service
metadata:
  name: web-app-service 
spec:
  type: NodePort
  ports:
  - port: 80 # port service
    targetPort: 80 #port container
    nodePort: 30082 #port node
  selector:
        app: nginx-app
